spring:
  datasource:
    username: root
    password: oldpassword_AA12
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379
server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.shiguang.springbootmybatis.entity  # 注意：对应实体类的路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
